SET ERHOME=%~dp0..
rem SET ERHOMEFOLDERNAME=ERmodel_v1.6
SET BUILDAREA=%ERHOME%\..\..\BuildArea
SET SAXON_PATH=%BUILDAREA%\thirdparty\SaxonHE11-4J
SET SAXON_JAR_NAME=saxon-he-11.4.jar
SET SAXON_JAR=%SAXON_PATH%\%SAXON_JAR_NAME%
SET JING_PATH=%DISTRIBUTION%\thirdparty\jing-20091111\bin