echo setting path variables
SET ERHOME=%~dp0..
SET ERHOMEFOLDERNAME=ERmodel_v1.6
SET DISTRIBUTION=%ERHOME%\..
SET SAXON_PATH=%DISTRIBUTION%\thirdparty\SaxonHE12-5J
SET SAXON_JAR_NAME=saxon-he-12.5.jar
SET SAXON_JAR=%SAXON_PATH%\%SAXON_JAR_NAME%
SET JING_PATH=%DISTRIBUTION%\thirdparty\jing-20091111\bin