SET DOCHOME=%~dp0..
SET ERSCRIPTHOME=%DOCHOME%\..\ERScript_r5
SET JING_PATH=%ERSCRIPTHOME%\thirdparty\jing-20091111\bin
SET SAXON_PATH=%ERSCRIPTHOME%\thirdparty\SaxonHE11-4J
SET SAXON_JAR_NAME=saxon-he-11.4.jar
SET SAXON_JAR=%SAXON_PATH%\%SAXON_JAR_NAME%
